project:
  type: book
  output-dir: docs
  
  
book:
  title: "Statistics and Machine Learning"
  author: "Nguyen Pham Nguyen The"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

toc: true
echo: false

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    code-copy: true
    fig-format: svg
    toc-expand: 3

editor: visual

